FluidityProject/fluidity

schemas/adaptivity_options.rnc
schemas/adaptivity_options.rng

This changes the adaptivity options schema to allow the FieldWeightedPartitionValues to be a diagnostic field. This lets you set spatially dependent weights for load balancing that aren't from a file/python function, etc.

Changed schema for the FieldWeightedPartitionValues

---

femtools/tictoc.F90
main/Fluids.F90
main/Makefile.dependencies

Added tictoc calls to calculate and print out the time spent in each timestep. This excludes the time spent in mesh adapts (if applicable), which is already calculated using separate tictoc calls.

Tictoc calls for every timestep

---

assemble/Advection_Diffusion_CG.F90
assemble/Advection_Diffusion_DG.F90
assemble/Advection_Diffusion_FV.F90
assemble/Momentum_CG.F90
assemble/Momentum_DG.F90

This is a possible fix for issue #46 .

Remove the asserts following cache prepopulation with openmp as there's no reason they can't be false.

---

configure
configure.in
libadaptivity/adapt3d/src/Adaptivity.cpp
libadaptivity/configure
libadaptivity/configure.in
libadaptivity/metric_field/src/DiscreteGeometryConstraints.cpp
libadaptivity/metric_field/src/ErrorMeasure.cpp
libadaptivity/metric_field/src/MetricTensor.cpp
libvtkfortran/vtkfortran.cpp
libvtkfortran/vtkmeshio.cpp
python/fluidity/diagnostics/vtutools.py
python/vtktools.py
tests/Helmholtz-anisotropic-vector-mms-p1p1cg-unstructured/Helmholtz-anisotropic-vector-mms-p1p1cg-unstructured.xml
tests/lock_exchange_2d_cg/lock_exchange_2d_cg.xml
tests/square-convection-dg/square-convection-dg.xml
tests/water_collapse_2d/water_collapse_2d.xml
tools/genpvtu.py
tools/mean_flow.py
tools/vtkdiagnostic.cpp
tools/vtkprojection.cpp
tools/vtu2ensight.py

This merge adds support for VTK6, authored by Mark Goffin. Modifications are made to configure scripts to pick up VTK's major version, and the codebase and tests modified to allow for pre- and post-6.0 behaviour. This has been tested on the standard Ubuntu Trusty build for VTK5 and on a CentOS 7 builder for VTK6. A minor tweak is also added to a Helmholtz test to fix tolerances for a full pass on CentOS 7.
Buildbot queues are at:
http://buildbot.ese.ic.ac.uk:8080/builders/add_vtk6_compatibility
http://buildbot.ese.ic.ac.uk:8080/builders/centos7-standard

Adding support for VTK6

---

tools/testharness.py

Prior to this merge, testharness can complete test runs but still exit with error if test it runs returns failures. This can be confusing as it suggests that testharness itself has experienced an error - a state which occurs if (for example) an invalid xml file is specified in the input. This commit removes the errant behaviour, and puts the onus on output parsers to detect whether or not tests are passing.

Change exit state of testharness following completed test runs

---

diagnostics/Surface.F90
schemas/diagnostic_algorithms.rnc
schemas/diagnostic_algorithms.rng
sediments/Sediment.F90
tests/surface_horizontal_divergence/Makefile
tests/surface_horizontal_divergence/src/slope.geo
tests/surface_horizontal_divergence/surface_horizontal_divergence.flml
tests/surface_horizontal_divergence/surface_horizontal_divergence.xml

This commit adds a new diagnostic field algorithm which collapses the last component of the coordinate field + an arbitrary vector field on a boundary surface, performs a horizontal divergence operation on this n-1 dimensional object, then continues this result back into the entire volume space.
Although the code has been written with the intention of using it to calculate a sediment bed load source term, the operator is slightly more general and thus made available outside this routine.

Add surface horizontal divergence diagnostic

---

python/fluidity/diagnostics/era.py
tests/netcdf_read_errors/createnetcdf.py
tests/netcdf_read_free_surface/createnetcdf.py

python-scientific is now unsupported; it doesn't work with numpy >= 1.9 and there are no plans to fix this, hence it's being dropped from most distros as numpy upgrades to 1.9 and beyond. We only use this for Scientific.IO.NetCDF which appears to be able to be replaced like-for-like with scipy.io.netcdf.
This commit makes that change.

Replace Scientific.IO.NetCDF with scipy.io.netcdf

---

configure
configure.in

Change purely in configure system:
In VTK 6.2, vtkXMLPUnstructuredGridWriter::new() has been moved from libvtkIOXML to libvtkIOParallelXML; this is added to the list of VTK libraries checked at configure time.
Note that this is still assuming 'standard' VTK library naming; Ubuntu's packaging of VTK6 does significant renaming of libraries and will need a far more comprehensive fix. This change is particularly targetted at Fedora 23's VTK6.3 packaging.

Updating VTK checks for vtk-6.2

---

configure
configure.in
femtools/Read_GMSH.F90

This commit adds an autoconf test to look for the intel advancing io bug. If found, it sets a preprocessor symbol such that the workaround code gets called, otherwise it is ignored. I _think_ this is the best way of dealing with the whole problem, given multiple compiler versions and Intel's habit of reintroducing old bugs into the latest versions of ifort.

configure level test for intel advance bug.

---

assemble/Coriolis.F90
error_measures/Limit_metric.F90
femtools/Field_Options.F90
tools/make_check_options.py

This is probably worth a pull request. It's the code written to deal with issue #50, where check_options routines are only auto detected when written in a specific pattern, whereas other patterns are both valid fortran, and used in the code base. It'll need a buildbot queue.

Changes to allow all check_options tests to run.

---

python/fluidity/diagnostics/era.py
tests/netcdf_read_errors/createnetcdf.py
tests/netcdf_read_free_surface/createnetcdf.py

As James presciently pointed out, this one has come back to bite us: turns out that the scipy shipped with CentOS 6 doesn't support the upper case naming convention, hence changing to a lower case plus underscores version.

Changing to scipy lower case namespace for NetCDF

---

Makefile.in
configure
configure.in
libjudy/Makefile.in
libwm/Makefile.in
libwm/Wm4Intersector.cpp
libwm/Wm4Intersector.h
libwm/Wm4Intersector1.h
libwm/Wm4IntrQuad2Quad2.h
libwm/Wm4IntrTetrahedron3Tetrahedron3.h
libwm/Wm4IntrTriangle2Triangle2.h
tests/add_src_directly_1d_2grp_hom_zerobc_eig_fv/Makefile
tests/add_src_directly_1d_2grp_hom_zerobc_eig_fv/add_src_directly_1d_2grp_hom_zerobc_eig_fv.xml
tests/add_src_directly_1d_2grp_hom_zerobc_eig_p1cg/Makefile
tests/add_src_directly_1d_2grp_hom_zerobc_eig_p1cg/add_src_directly_1d_2grp_hom_zerobc_eig_p1cg.xml
tests/add_src_directly_1d_2grp_hom_zerobc_eig_p1cv/Makefile
tests/add_src_directly_1d_2grp_hom_zerobc_eig_p1cv/add_src_directly_1d_2grp_hom_zerobc_eig_p1cv.xml
tests/add_src_directly_1d_2grp_hom_zerobc_eig_p1dg/Makefile
tests/add_src_directly_1d_2grp_hom_zerobc_eig_p1dg/add_src_directly_1d_2grp_hom_zerobc_eig_p1dg.xml
tests/gauss_point_buoyancy/gauss_point_buoyancy.xml
tests/geopressure_convergence/Makefile
tests/geopressure_convergence_p1/Makefile
tests/geopressure_convergence_p3/Makefile
tests/petsc_readnsolve/Makefile
tests/petsc_readnsolve/petsc_readnsolve.xml
tests/python_shape_dshape_test/Makefile
tests/python_shape_dshape_test_2d/Makefile
tests/tools.mk.in

A collection of changes to configure etc. to make building on Mac OSX easier. These come in two flavours:
1) Changes required due to a BSD-based environment in which the gnu toolchain may be harder to find, for which there are variations in compiler flags
2) Changes to deal with the possibility of a case-insensitive file system.
There are also two changes to tests proposed, one to deal with problems accessing lib spud from inside the embedded python interpreter and a tolerance relaxation to one of @cianwilson's tests.
@tmbgreaves Could I get a buildbot queue for this as well please?

Mac friendly configuration

---

tools/Fladapt.F90

It appears Fladapt.F90 is causing an internal compiler error on CX1. This commit fixes that file for intel.

Fix fladapt on CX1.

---

tests/channel-flow-dg/channel_viscous.flml
tests/no_normal_flow_dg/no_normal_flow.flml
tests/prescribed_normal_flow_dg/presc_normal_flow.flml

As I reported in #101, It appears that hypre - euclid isn't a preconditioner option available in recent Petsc - at least as compiled by us. This change set switches the tests that use it to cg + boomerAMG / gmres+sor.
@tmbgreaves: Is there a way of just testing the test changes under the buildbot environment? It seems like overkill to build a whole branch for just this?

Change tests attempting to use the Euclid preconditioner

---

assemble/Mba3d_Integration.F90
femtools/Bound_field.F90
femtools/Diagnostic_variables.F90
femtools/Embed_Python_Fortran.F90
femtools/Global_Parameters.F90
femtools/Grundmann_Moeller_Quadrature.F90
femtools/MPI_Interfaces.F90
femtools/Node_Owner_Finder_Fortran.F90
femtools/Profiler_Fortran.F90
femtools/Read_Exodusii.F90
femtools/Supermesh.F90
femtools/Timers.F90
femtools/Vertical_Extrapolation.F90
femtools/Wandzura_Quadrature.F90
femtools/qsortd.F90
femtools/tests/test_vtk_precision.F90
ocean_forcing/ClimateReader_interface.F90
ocean_forcing/FluxesReader_interface.F90
ocean_forcing/NemoReader_interface.F90

This changeset attempts to deal with the issue raised in #109 by explicitly replacing the kind parameters with those from iso_c_binding in all cases.

Use iso_c_binding kind names.

---

femtools/Conservative_interpolation.F90
femtools/Intersection_finder.F90
femtools/Supermesh.F90
femtools/tests/test_intersection_finder_completeness.F90
femtools/tests/test_intersection_finder_completeness_3d.F90
femtools/tests/test_quad_supermesh.F90
femtools/tests/test_tet_intersector.F90
femtools/tests/test_unify_meshes.F90

This changeset short circuits the vanilla 2d intersection code so that it doesn't pointlessly allocate a vector field when run with "false alarm" elements which touch at a point or edge rather than overlapping. The original version has a significant penalty when running Galerkin projection to interpolate between meshes which are almost identical, and it seems we do something similar by default in 3d anyway.

Intersection optimisation

---

configure
configure.in
libadaptivity/configure
libadaptivity/configure.in

This pull request attempts to implement @stephankramer's cmake based fix for finding where the elves have hidden VTK on an arbitrary system, issue #113. So far it doesn't remove anything, the only time it might change behaviour is when cmake isn't available, but the location of VTK has been implicitly provided through environment flags.

Implementing Stephan's fix for finding VTK.

---

manual/python.tex
python/fluidity_tools.py

The existing fluidity_tools method to get an interactive python shell no longer works with a modern version of IPython (i.e. in the last 4 years or so). Based on an offline discussion with @stephankramer this pulls the failing code out and updates the manual to give a generic version which should work.

Update manual text on interactive shell.

---

libvtkfortran/vtkfortran.cpp

This is a bug-fix really - but I'd appreciate if @jrper could have a quick look to check it.
The hack that allows us to write the vtus of a pvtu into a
sub-directory, involves the following step:
1) create the subdirectory, and tell vtk to write the pvtu and vtus into
that subdirectory
2) move the pvtu to the directory above
3) fix the paths in the pvtus to relative paths into the subdirectory
Steps 2) and 3) are done by process 0. But currently no steps are taken
to ensure the other processes are actually finished with 1).
This change puts a barrier between 2) and 3) to avoid a race condition
that causes the pvtu to get mangled (observed on Debian unstable with
vtk 6.3).

Fix race condition in writing pvtus.

---

libspud/include/spud
libspud/src/spud.cpp

To avoid a destructor being called twice (due to optimisation removing a
variable), deallocated is defined as static in libspud/include/spud and then
defined in libspud/src/spud.cpp.
Fix supplied by James Percival (jrper)

UPSTREAM BUGFIX for libspud

---

diagnostics/Makefile.dependencies
diagnostics/Mesh_Diagnostics.F90
femtools/Makefile.dependencies
femtools/Makefile.in
femtools/Mesh_Quality.F90
femtools/Mesh_Quality_C.cpp
schemas/diagnostic_algorithms.rnc
schemas/diagnostic_algorithms.rng
tests/mesh_quality/Makefile
tests/mesh_quality/mesh_quality.flml
tests/mesh_quality/mesh_quality.xml
tests/mesh_quality/src/square.geo

This changeset allows the user to specify a mesh quality function from VTK as a fluidity diagnostic field. The intention is that this can be used to control h- and connectivity based mesh adaptivity in the context of moving meshes.

Add mesh quality functions from vtk as fluidity diagnostics.

---

configure
configure.in

This minor change to the configure script attempt to make the behaviour of the PYTHON_VERSION environment variable consistent between searching for python and numpy.

Make numpy configuration consistent with the rest of the python code.

---

femtools/Conservative_interpolation.F90
femtools/Intersection_finder.F90
femtools/Supermesh.F90
femtools/tests/test_intersection_finder_completeness.F90
femtools/tests/test_intersection_finder_completeness_3d.F90
femtools/tests/test_quad_supermesh.F90
femtools/tests/test_unify_meshes.F90
tools/Vertical_Integration.F90
tools/unifiedmesh.F90

The optimisation in commit c68550e5d8fb700ecf1c6acda28f66b00eb2d465
introduced a short-cut in intersect_elements() where if the intersection
was found to be empty it no longer bothered to allocate a valid
0-element mesh. This condition had to then be catched
by always checking with has_references() on the returned mesh. On second
thought this is a little flaky. If a function returns an
allocated femtools object it should always return a valid object - or
there should be some other mechanism to indicate the function result
should be discarded (e.g. extract_scalar_field with a stat argument).
In this spirit, intersect_elements() now has an optional
empty_intersection argument. The short-cut is only invoked if this
argument is provided  - thus restoring the semantics from before the …

Fix bugs related to intersect_elements() short-cut.

---

schemas/flredecomp.rnc
schemas/flredecomp.rng
tests/detectors_parallel_init/detectors.flml

The schema currently isn't spud base language compliant when setting the partitioner option for zoltan (graph|hypergraph) under flredecomp. 
This commit fixes that and updates the only test that currently uses this option. Thanks to Cian for highlighting the issue.
Buildbot branch here:
http://buildbot-ocean.ese.ic.ac.uk:8080/builders/zoltan-option-schema-fix

Make schema spud base language compliant for flredecomp zoltan option

---

configure
configure.in
m4/ACX_lib_automagic.m4

This changeset attempts to improve the behaviour of the configure script in searching for the netcdf Fortan interface library (libnetcdff). Without these changes, there are issues with the shared library build.

Fix libnetcdff configure

---

Makefile.in

Hi Tim,
James and I spotted a problem when cleaning the libspud library in CX1.
We added the abspath to the SPUDLIB so it returns an absolute name of the library without getting confuse with the CX1 path names.

Fix to make clean in libspud for CX1

---

assemble/Full_Projection.F90
assemble/Momentum_CG.F90
femtools/Multigrid.F90
femtools/Solvers.F90
femtools/Sparse_Tools_Petsc.F90
python/fluidity_tools.py
schemas/prognostic_field_options.rnc
schemas/prognostic_field_options.rng
tests/Stokes_may_sinker_stepxy/Stokes-may-sinker-stepxy-gamg.flml
tests/Stokes_may_sinker_stepxy/Stokes_may_sinker_stepxy.xml

This PR does two things:
* it fixes the cache_solver_context option under the solver/ options of  scalar prognostic fields. It was creating a new ksp regardless of the option, so the only thing it did was create a memory leak by not destroying the previous one. This is now fixed. It's still a bit of a feeble option as it relies on users to know whether a matrix changes between subsequent solves.
* it introduces reusing of the ksp for momentum solves. This only applies for full_momentum or mass_matrix solves where there are in fact 3 different places that require setting up of a ksp for a momentum solve:
1) the initial velocity solve
2) the "inner" velocity solve of the Schur complement solve in the pressure projection
3) the velocity correction
Solver options for 1) are directly under …

Ksp caching

---

tests/Stokes_Poiseuille/Makefile
tests/Stokes_Poiseuille/Setup.py
tests/Stokes_Poiseuille/Stokes-Poiseuille.flml
tests/Stokes_Poiseuille/Stokes_Poiseuille.xml
tests/Stokes_Poiseuille/mesh/Rectangular_Pipe.geo

This branch adds a new test case to Fluidity, which is the classical two-dimensional Poiseuille flow in a rectangular cartesian domain. Fluidity solves for the Pressure and the Velocity. The values of the Velocity are then compared to the well-known analytical solution, which depends on the Pressure Gradient that Fluidity works out as well.
Everything seems to work well, however two remarks :
- the pressure boundary conditions are weakly applied, which requires to turn ON "scalar_field (Pressure)/prognostic/spatial_discretisation/continuous_galerkin/integrate_continuity_by_parts". If it is OFF, Fluidity does not raise any Error or Warning and the calculated Pressure field is zero.
- calculating the Pressure Gradient in Fluidity requires to add a FiniteElementGradient field, however the …

Poiseuille test case

---

include/petsc_legacy.h

PETSc major version is added in testing in case minor version testing only will break after 4.0 is released.

Include PETSc major version in testing

---

configure
configure.in
libvtkfortran/configure
libvtkfortran/configure.in
libvtkfortran/vtkfortran.cpp

It appears that since about VTK 6.3, their code now uses parallel communication to identify which pieces of a parallel file have been written. See line 213 and onward in their github repository [here](https://github.com/Kitware/VTK/blob/3276be1e1f3d44eb403ebda9ad589869c5b7d4bf/IO/ParallelXML/vtkXMLPDataObjectWriter.cxx). 
The net result on an unlucky setup is that our VTK writers produce a summary .pvtu file referencing only one of the .vtus, even though they have all been written. This changeset attempts to deal with this by doing the necessary work to allow the MPI communication to succeed, but has only been tested locally on one system. Possibly @jmn114 might be able to assist with testing.

Update vtkfortran for VTK MPI communication.

---

configure
configure.in
libvtkfortran/configure
libvtkfortran/configure.in
libvtkfortran/vtkfortran.cpp

VTK introduced the MPI communication after, rather than before, version 6.3. Fix this by checking for VTK_MAJOR_VERSION > 6 (and excluding minor version checks). Tested locally but should probably go through buildbot. @tmbgreaves could you set up a buildbot and trigger it? If all goes green, I'm hoping @jrper can quickly check, approve and merge.

VTK Fortan MPI communication: Version --> 7

---

Jenkinsfile
docker/Dockerfile.centos
docker/Dockerfile.ubuntu
tests/netcdf_read_errors/netcdf_read_errors.xml
tests/unresolvable_diagnostic_dependency/unresolvable_diagnostic_dependency.xml
tests/unresolvable_diagnostic_dependency2/unresolvable_diagnostic_dependency2.xml
tests/unresolvable_mesh_dependency/unresolvable_mesh_dependency.xml

Adding Jenkins support for Fluidity. This commit adds a template Jenkinsfile which runs the basic tests on a non-debug build, working from base images on dockerhub built from Dockerfiles included in the docker/ directory in this repository. 
Issues with netcdf_read_errors are addressed, where the mount point for jenkins-derived filesystems in the docker build agent are long enough to trigger false warnings about broken /proc/mounts, which pollute the expected error output. A sed hack is introduced to deal with this. This problem *should* be dealt with by any recent hwloc as included in OpenMPI 3.0 and later, so the sed hack can probably be backed out in the not too distant future.
Three other tests looking at error output are returning wierd results and are provisionally turned off so as …

Jenkins initialisation

---

Jenkinsfile
python/fluidity/regressiontest.py
tools/testharness.py

These changes fix an important oversight in the testharness junit support, which meant two test failures on the Jenkins Centos7 build weren't being picked up. Further, it adds Slack notifications to the Jenkinsfile, as well as marking unstable builds as failed on Jenkins, in a method that could be extended if we want e.g email notifications of master build failures.
For the record, the 2 centos failures are `vtu2ensight`, due to missing files in the vtk support and `gls-ocean-param`, apparently due to `matplotlib` issues.

Test harness bug fix plus Jenkins slack integration

---

error_measures/tests/test_simplex_tensor_edgelens.F90
femtools/Futils.F90
femtools/Intersection_finder.F90
femtools/tests/test_matmul_t.F90
tests/diamond_validation/diamond_validation.xml
tests/popbal_nonhomog2_2d_adapt/popbal_nonhomog2_2d_adapt.xml
tests/popbal_nonhomog2_2d_cg_p1/popbal_nonhomog2_2d_cg_p1.xml
tests/popbal_nonhomog2_2d_cg_p2/popbal_nonhomog2_2d_cg_p2.xml
tests/popbal_nonhomog2_2d_dg_p1/popbal_nonhomog2_2d_dg_p1.xml
tests/popbal_nonhomog2_2d_dg_p2/popbal_nonhomog2_2d_dg_p2.xml
tests/popbal_nonhomog_2d_adapt/popbal_nonhomog_2d_adapt.xml
tests/popbal_nonhomog_2d_cg_p1/popbal_nonhomog_2d_cg_p1.xml

Dear all,
Following #192, I have created a branch https://github.com/FluidityProject/fluidity/tree/FixTests to fix the few tests that fail.
For now, I have not looked through the ```make unittest``` call.
For the ```make test``` call, ```mmat-interpolation-2d-parallel.xml``` and ```square-convection-parallel-trivial.xml``` fail because of an assertion at line 209 in femtools/Intersection_finder.F90. I considered it to be unnecessary (which may not be true) and thereby I commented it, which allowed both tests to pass (apologies for the diff result, my text editor automatically gets rid of the white spaces on blank lines). ```coarse-corner-limited.xml``` fails to achieve an error smaller than 1e-1 for the last part of the test; it results in a 1.01e-1 value on my machine. Do you think …

Failing tests on Ubuntu 18.04 Bionic

---

include/petsc_legacy.h
tools/petsc_readnsolve.F90

I can't figure out why this compiles in its current state, although not on my configuration. Currently, a null `VecScatter` object is passed through to an `IS` parameter. This should affect PETSc versions 3.8 and up, where typed null objects were introduced.

Correct types in call to PETSc (3.8+) VecScatterCreate()

---

femtools/Solvers.F90
include/petsc_legacy.h

PETSc saw `MatSolverPackage` renamed to `MatSolverType`, this has been reflected in the petsc_legacy.h overrides. Hopefully this doesn't step on the toes of #218 which first raised the issue.

Support PETSc 3.9

---

femtools/Fields_Base.F90
femtools/Transform_elements.F90
tests/spherical_mappings_2d/analytic.flml
tests/spherical_mappings_2d/linear.flml
tests/spherical_mappings_2d/spherical_mappings_2d.xml
tests/spherical_mappings_2d/super.flml
tests/spherical_mappings_2d/super_analytic.flml

Fixes orientation of normals in the super-parametric case. In this case it is not necessarily true that the vector between element centroid and facet centroid is in the same direction as the normal. Instead choose orientation using the local coordinate associated with the opposite vertex (requires dn_s, derivatives of element shape functions evaluated at the facet).

Fix normal orientation

---

aclocal.m4
configure
configure.in

Versions of Python 3 may be tagged according to their ABI version (PEP 3149), e.g. `3.7m`, however the current `AC_PYTHON_DEVEL` macro is unable to detect this, leading to a discrepancy between `PYTHON_VERSION` and the libraries it attempts to link against. This updates the macro to the latest aclocal-contrib version, while retaining the custom behaviour for OSX in 139814b57 ("Minimal changeset to configure and build successfully with python 3.x.", 2018-03-07).
I'm not really sure of the status of the autotools vs. CMake build systems, so hopefully this isn't misplaced!

Update AC_PYTHON_DEVEL aclocal macro

---

Jenkinsfile

Jenkins is missing a make makefiles - add one to the testing suite.

Add in 'make makefiles' test in Jenkins

---

femtools/Fields_Allocates.F90

I discovered this while trying to make an Intel-compiled executable run. This bug fix isn't specific to that, so I've broken it into its own PR.

Correct bug in make_mesh_periodic

---

assemble/Momentum_CG.F90
assemble/Multiphase.F90
horizontal_adaptivity/Extrude.F90
parameterisation/k_epsilon.F90
population_balance/DQMOM.F90

In a few places, an array will be allocated or a pointer associated depending on a logical flag. These subroutines then call another subroutine, passing the array/pointer and the flag. However, the dummy argument to this second subroutine doesn't have the `allocatable` or `pointer` attributes. Depending on the flag, we may be passing an unallocated array or unassociated pointer to a bare dummy argument, which is not allowed. To be compliant, we should specify these attributes, even for `intent(in)` dummy arguments, where the allocated/associated status is not allowed to change (this is a Fortran 2003-ism in the case of pointers).
For an example of the pattern:
```fortran
subroutine construct_momentum_element_cg(...)
real, dimension(:,:,:), allocatable :: dnvfrac_t
if (multiphase) then …
```

Prevent unallocated/unassociated actual arguments

---

tools/statplot.py

I had already proposed this idea in this now-closed [issue](https://github.com/FluidityProject/fluidity/issues/236) where I tried to show that many files in the Fluidity tree are currently involved in the file-reading process of statplot.
I believe that the current situation is too complex for what it should be and therefore I hereby propose a standalone version of statplot.
Changes compared to the master branch are summarized in the two commit messages. Instructions relative to the implemented keyboard shortcuts are available through `statplot.py --help`.
I am happy to modify further and implement new features if requested.

Statplot as a standalone

---

tools/statplot.py

I did not realise that keys pressed (apart from a's, o's and the ones without a function) would still have an effect on the window while writing in the combo boxes. For example, open any statfile, press o to have access to the bottom right combo box and then press q: the GUI shuts down. This commit fixes the issue.
Sorry again.

Sorry, this just showed up.

---

femtools/Sparse_Tools.F90
femtools/tests/test_block_csr_transpose_symmetric_sparsity.F90

PETSc 3.13 added is_sorted as an enum hence causing
a compiler conflict.
Fixes issue #266.

Remove is_sorted allowing configure with PETSc3.13

---

femtools/Transform_elements.F90

The second dimension of J should be the surface dimension (i.e. dim-1),
otherwise the matmul in line 2326 does not match. This is copying a
smaller array into a larger, so should be safe - and I can't actually
get my compiler to complain (even with debugging) - but this should
hopefully fix #206.

Fix wrong Jacobian dimensions in transform_cvsurf_to_physical.

---

assemble/Momentum_Equation.F90
femtools/FETools.F90
femtools/Fields_Calculations.F90
femtools/Makefile.dependencies
femtools/Solvers.F90

This performs a big L2 projection after the final velocity correction if a nullspace has been specified for Velocity, i.e. it ensure that the final velocity is L2 orthogonal to the specified nullspace. This is to avoid spurious rotations (or translations) that may occur with variable resolution. During the (petsc) solves the nullspace is projected out in the small l2-norm. However if for example the mesh resolution is biased where there are e.g. the same number of nodes with clockwise rotation as there are nodes with counter-clockwise rotation, but the nodes with clockwise rotation are very much concentrated in small area, then in an L2-integrated sense the solution still has a net counter-clockwise rotation (as the same number of associated nodes represent more area).
A possibly …

Big L2 nullspace projection

---

assemble/Zoltan_callbacks.F90

This is in the partioning of the horizontal mesh. The weight for each
column is determined by the number of layers in that column. This weight
was then divided by the maximum number of layers, however the maximum
was not computed globally, so this scaling causes an imbalance between
partititions with many layers and those with few layers. Establishing
the global maximum (allmax) would probably cause a hang as this is inside a zoltan callback. Therefore just remove the scaling. This might give a different weighting of nodal vs. edge weights - but it's unclear what is the right answer.
Fixed #114.

Remove erronous scaling of extruded partioning weights

---

tests/netcdf_read_free_surface/height.py

The `bivariate_normal` function was removed from matplotlib's mlab modules [in 3.1.0](https://matplotlib.org/api/prev_api_changes/api_changes_3.1.0.html?highlight=bivariate_normal#matplotlib-mlab-removals). Using `multivariate_normal` from scipy (as of 0.14.0) can replicate the same behaviour: the maximum absolute difference is about 5e-16 (matplotlib 2.1.1, scipy 0.19.1, Python 2.7.15).
Making this change fixes the *netcdf_read_free_surface* test case with recent matplotlib versions.

Fix netcdf_read_free_surface with modern matplotlib

---

femtools/Particles.F90

Because particles are uniquely identified by a (node, proc) ID pair, we need to output both these properties for diagnostics.

Write particle processor IDs to output

---

tests/python_validation/python_validate.py
tests/python_validation/python_validation.xml

Since we no longer expect to maintain backwards compatibility, this test is generating unnecessary warnings.

Remove Python 2 from python_validate test

---

python/fluidity/regressiontest.py

`time.clock()` was removed in Python 3.8 (and deprecated since Python 3.3). Use `time.process_time()` instead, which gives the sum of system and user CPU time, but doesn't include time elapsed during sleep.
I don't quite know the context for the current call: if doesn't seem to be measuring a particularly tight loop, so I don't think `time.perf_counter()` is necessary.

Change time.clock() to time.process_time()

---

femtools/Solvers.F90

This simply changes the output variables from NULLs to Fortran integers because gfortran was complaining about the types of the arguments passed to store the output, we don't actually use these output variables anywhere, so this should change absolutely nothing result or performance wise.
Fixes #292

Fix compilation issues with PETSc 3.13+

---

assemble/qmesh.F90
femtools/Write_State.F90
tools/petsc_readnsolve.F90

Fixes Division by zero in Write_State.F90 #289
Fortran does not have short-circuit evaluation!
NOTE: I am not sure I have removed all the short-circuit expressions.
I do believe however that I have removed all the divs by 0 in mod.
Validated using Rust flavoured regex: `mod\((.*)\)(\s*?)`
-------
This should probably be merged to master before the focal update or merged into the focal update PR

Fix short-circuit evaluation division by zero GCC v9+

---

femtools/Makefile.dependencies
femtools/Read_GMSH.F90
python/fluidity/diagnostics/gmshtools.py
tests/channel-flow-dg/channel.py
tests/channel-flow-dg/channel_viscous.py
tests/diffusion-dg-stretched/makebox.py
tests/mms_tracer_P1dg_cdg_diff_steady_3d_cjc/cdg3d.py
tests/mms_tracer_P1dg_cdg_diff_steady_3d_cjc_inhNmnnbc/cdg3d.py
tests/spherical_patch/src/spherical_segment.geo
tests/wetting_and_drying_balzano1_cg/mesh/makemesh.sh
tests/wetting_and_drying_balzano2_cg/mesh/makemesh.sh
tests/wetting_and_drying_balzano3_cg_parallel/Makefile
tests/wind_stratification/Makefile

This builds on the issue raised in #233 and https://github.com/FluidityProject/fluidity/commit/c41e5e54fc7e169c620b10d30058d7fd2918f788. On my local build, all tests pass except for one on `spherical_segment`, due to some changes in GMSH itself.
This support would introduce a new dependency on the Python [meshio](https://github.com/nschloe/meshio) library for the `gmsh_mesh_transform` and `transform_mesh` tools, which currently expect ASCII MSH files and modify them directly. I think it's probably a more robust solution to abstract these mesh modifications through some kind of library anyway.

GMSH v4 support

---

femtools/embed_python.c
femtools/python_statec.c

Often when an error occurs in the python embedded in fluidity, the
error+backtrace would not show up despite use calling PyErr_Print and
only prints the useless FLAbort message "Dying!". This
is caused by some internal buffering in python of stdio and stderr
(internal to python so independent of whether we have redirected the
actual stdio/stderr of the process at the system level). This commit
switches all such buffering off. As suggested here:
https://stackoverflow.com/questions/29352485/python-print-not-working-when-embedded-into-mpi-program/49076389#49076389
under option 1) Note that it should only affect stdio/err and not all
I/O from python (as it claims on stackexchange), and since we
shouldn't normally be printing much from python this should hopefully
not affect performance.
Also …

Improved error messages from python

---

assemble/Zoltan_callbacks.F90
assemble/Zoltan_detectors.F90
assemble/Zoltan_integration.F90
femtools/Detector_Parallel.F90
femtools/Detector_Tools.F90

(Duplicated from #319)
When we allocate/unpack detectors from Zoltan, some code expects that their attribute arrays (used for particles) are at least allocated, even if length 0. Ensuring this is done avoids potential segfaults when these arrays are unconditionally accessed.
Thanks @stephankramer for the detailed analysis of this issue! I think this is probably the right place for this allocation? Of course, the other approach would be to figure out where attribute_size is being passed into unpack_detector as a non-optional on a detector. (As an aside, that subroutine looks like it could just take a non-optional attribute_size and then the logic wouldn't be exactly duplicated in both branches...)
Closes #317.

Allocate empty attribute arrays for detectors

---

aclocal.m4
assemble/Full_Projection.F90
assemble/tests/test_matrix_free.F90
assemble/tests/test_pressure_solve.F90
configure
configure.in
femtools/ISCopyIndices.cpp
femtools/Multigrid.F90
femtools/Petsc_Tools.F90
femtools/Solvers.F90
femtools/Sparse_Tools.F90
femtools/Sparse_Tools_Petsc.F90
femtools/tests/test_matrix_conversions.F90
femtools/tests/test_multigrid.F90
femtools/tests/test_petsc_csr_matrix.F90
include/config.h.in
include/petsc_legacy.h
manual/external_libraries.tex
tools/petsc_readnsolve.F90
tools/petsc_readnsolve_main.cpp
tools/test_laplacian.F90
tools/test_pressure_solve.F90

This is dealing with bug https://gitlab.com/petsc/petsc/-/issues/868
Which is fixed only for 3.15. Unfortunately no workarounds for 3.14 exists in fortran,
because even if we do provide the optional argument it still gets
recognized for NULL and hits the bug. So instead write our own wrapper
in C.
This also drop support for petsc version <3.8 Note that Bionic official
packages are 3.7 - but we have always supplied our own 3.8 package for
it. Groovy and Hirsute are now on 3.14 Dropping support for <3.8
simplifies/removes a lot of the legacy workarounds. We no longer support
linking with petsc without fortran modules (we never did for versions >=3.8).

Fix "mg" preconditioner with petsc 3.14

---

.gitignore
femtools/.gitignore
femtools/Fields_Allocates.F90
preprocessor/Populate_State.F90
sediments/Sediment.F90
tests/.gitignore
tests/Helmholtz-anisotropic-scalar-mms-p1p1cg-structured/Makefile
tests/Stokes_square_convection_1e4_p1p1_parallel/Makefile
tests/Stokes_square_convection_1e4_p1p1cv/Makefile
tests/add_src_directly_1d_2grp_hom_zerobc_eig_fv/Makefile
tests/add_src_directly_1d_2grp_hom_zerobc_eig_p1cg/Makefile
tests/add_src_directly_1d_2grp_hom_zerobc_eig_p1cv/Makefile
tests/add_src_directly_1d_2grp_hom_zerobc_eig_p1dg/Makefile
tests/analytical-sphere-cg-tracer/Makefile
tests/bc-smoothing/Makefile
tests/biology_conservation/Makefile
tests/biology_conservation_adapt/Makefile
tests/flredecomp_repart/Makefile
tests/parallel_refinement_2d/Makefile
tests/particle_attributes_checkpoint_parallel_flredecomp/Makefile
tests/prescribed_adaptivity_spaces/Makefile
tests/sigma_layer_sphere_parallel/Makefile
tests/sloshing_tank/Makefile
tests/square-convection-parallel/Makefile
tests/square-convection/checkpoint/Makefile
tests/standing_wave-dg-adapt/Makefile

While doing some work I encountered one more short-circuit evaluation in Sediments along with some compiler failures
when enabling for using recursion in routines not marked as such (you can replicate the failures by turning -fcheck=recursion` on during compilation).
I also fixed some of the `clean` targets in our test Makefiles because they were polluting the git tree after running tests.
1. Fixes short circuit evaluations in sediments
2. Adds missing recursion keyword for subroutines that are used in recursion
3. Edits some make files in tests to completely clean the test output
4. Made `.gitignore` slightly more aggressive to specifically ignore all the configure and compile generated files and nothing more
I believe this is now done.

Minor bugs spotted in Focal

---

.github/workflows/ubuntu.yml

GitHub has made some changes to Actions (links below), and as a result, versions of actions used in our workflows should be updated.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Update versions of actions to avoid deprecation warnings

---

femtools/GMSH_Common.F90

Use a 64 bit int for the position to prevent an overflow with big meshes
